version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: "20230801161711944"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
